spring:
  application:
    name: webflux-websocket
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
server:
  port: 8082
  servlet:
    context-path: /